/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminApproval {
  'status' : string,
  'contentId' : string,
  'creator' : Principal,
  'feedback' : string,
  'approvalDate' : [] | [Time],
  'submissionDate' : Time,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BulkUploadItem {
  'title' : string,
  'coverImagePath' : string,
  'trailerPath' : string,
  'description' : string,
}
export interface Category {
  'name' : string,
  'description' : string,
  'iconPath' : string,
}
export interface ChatMessage {
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export type ContentResult = { 'fallback' : FeaturedContent } |
  { 'success' : FeaturedContent };
export interface CreatorShowcase {
  'profileImage' : string,
  'name' : string,
  'featuredWork' : string,
  'description' : string,
}
export interface CreatorSubmission {
  'contactInfo' : string,
  'filmTitle' : string,
  'description' : string,
  'creatorName' : string,
  'category' : string,
}
export interface CreatorVerification {
  'status' : string,
  'principal' : Principal,
  'verified' : boolean,
  'contactInfo' : string,
  'verificationDate' : [] | [Time],
  'creatorType' : string,
  'identityDocument' : [] | [string],
  'submissionDate' : Time,
}
export interface FeaturedContent {
  'categories' : Array<Category>,
  'featuredMovies' : Array<FeaturedMovie>,
  'creatorShowcases' : Array<CreatorShowcase>,
  'valueProps' : Array<ValueProp>,
  'trailerClips' : Array<TrailerClip>,
  'movies' : Array<Movie>,
}
export interface FeaturedMovie {
  'id' : string,
  'title' : string,
  'coverImagePath' : string,
  'trailerPath' : string,
  'description' : string,
  'director' : string,
  'genre' : string,
  'rating' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type List = [] | [[string, List]];
export type List_1 = [] | [[ChatMessage, List_1]];
export type List_2 = [] | [[Principal, List_2]];
export type List_3 = [] | [[Reaction, List_3]];
export type List_4 = [] | [[RoyaltyEvent, List_4]];
export type List_5 = [] | [[PayoutRecord, List_5]];
export interface Movie {
  'title' : string,
  'coverImagePath' : string,
  'trailerPath' : string,
  'description' : string,
  'averageRating' : bigint,
  'reviewCount' : bigint,
}
export type PaymentMethod = { 'icp' : string } |
  { 'mobileMoney' : string } |
  { 'stripe' : string } |
  { 'usdc' : string } |
  { 'usdt' : string } |
  { 'tamriWallet' : string } |
  { 'crypto' : string } |
  { 'paystack' : string } |
  { 'plugWallet' : string } |
  { 'stoicWallet' : string } |
  { 'mPesa' : string };
export interface PayoutRecord {
  'status' : string,
  'method' : PaymentMethod,
  'date' : Time,
  'amount' : bigint,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Rating { 'review' : string, 'score' : bigint }
export interface Reaction {
  'user' : Principal,
  'reactionType' : string,
  'timestamp' : Time,
}
export interface RevenueModel {
  'merchandise' : bigint,
  'subscriptionRevenue' : bigint,
  'adRevenue' : bigint,
  'payPerView' : bigint,
  'tipsDonations' : bigint,
}
export interface RevenueShare {
  'paymentMethod' : PaymentMethod,
  'payoutHistory' : List_5,
  'pendingPayouts' : bigint,
  'totalEarnings' : bigint,
}
export interface RoyaltyEvent {
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
  'amount' : bigint,
  'eventType' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SmartRoyalty {
  'contentId' : string,
  'creator' : Principal,
  'payoutHistory' : List_5,
  'lastUpdated' : Time,
  'revenueModel' : RevenueModel,
  'totalEarnings' : bigint,
  'eventLog' : List_4,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TopPick {
  'curatorName' : string,
  'recommendation' : string,
  'movieTitle' : string,
  'reason' : string,
}
export interface TrailerClip {
  'title' : string,
  'description' : string,
  'videoPath' : string,
  'thumbnailPath' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'watchPartyHistory' : List,
  'favoriteMovies' : List,
  'dataSaverMode' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValueProp {
  'supportingPoints' : Array<string>,
  'headline' : string,
  'description' : string,
}
export interface WatchParty {
  'id' : string,
  'startTime' : Time,
  'participants' : List_2,
  'host' : Principal,
  'isActive' : boolean,
  'movieTitle' : string,
  'reactions' : List_3,
  'chatHistory' : List_1,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFavoriteMovie' : ActorMethod<[string], undefined>,
  'addMovie' : ActorMethod<[string, string, string, string], undefined>,
  'addReaction' : ActorMethod<[string, string], undefined>,
  'addTopPick' : ActorMethod<[string, string, string, string], undefined>,
  'approveContent' : ActorMethod<[string, boolean, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUploadMovies' : ActorMethod<[Array<BulkUploadItem>], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createSmartRoyalty' : ActorMethod<[string, RevenueModel], undefined>,
  'createWatchParty' : ActorMethod<[string], string>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllContentApprovals' : ActorMethod<[], Array<AdminApproval>>,
  'getAllCreatorVerifications' : ActorMethod<[], Array<CreatorVerification>>,
  'getAllMovies' : ActorMethod<[], Array<Movie>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllSmartRoyalties' : ActorMethod<[], Array<SmartRoyalty>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentApprovalStatus' : ActorMethod<[string], [] | [AdminApproval]>,
  'getCreatorSubmissions' : ActorMethod<[], Array<CreatorSubmission>>,
  'getCreatorVerificationStatus' : ActorMethod<[], [] | [CreatorVerification]>,
  'getDataSaverMode' : ActorMethod<[], boolean>,
  'getFallbackContent' : ActorMethod<[], FeaturedContent>,
  'getFavoriteMovies' : ActorMethod<[], Array<string>>,
  'getFeaturedContent' : ActorMethod<[], ContentResult>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMovie' : ActorMethod<[string], [] | [Movie]>,
  'getMovieRatings' : ActorMethod<[string], Array<Rating>>,
  'getRevenueModel' : ActorMethod<[], RevenueModel>,
  'getRevenueShare' : ActorMethod<[], RevenueShare>,
  'getRevenueSharingInfo' : ActorMethod<[], Array<RevenueShare>>,
  'getRoyaltyEvents' : ActorMethod<[string], Array<RoyaltyEvent>>,
  'getRoyaltyPayoutHistory' : ActorMethod<[string], Array<PayoutRecord>>,
  'getSmartRoyaltiesByCreator' : ActorMethod<[Principal], Array<SmartRoyalty>>,
  'getSmartRoyalty' : ActorMethod<[string], [] | [SmartRoyalty]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopPicks' : ActorMethod<[], Array<TopPick>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchParty' : ActorMethod<[string], [] | [WatchParty]>,
  'getWatchPartyHistory' : ActorMethod<[], Array<string>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinWatchParty' : ActorMethod<[string], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'logRoyaltyEvent' : ActorMethod<[string, string, bigint, string], undefined>,
  'rateMovie' : ActorMethod<[string, bigint, string], undefined>,
  'registerCreator' : ActorMethod<[string, string, [] | [string]], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'removeFavoriteMovie' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMovies' : ActorMethod<[string], Array<Movie>>,
  'sendChatMessage' : ActorMethod<[string, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setDataSaverMode' : ActorMethod<[boolean], undefined>,
  'setPaymentMethod' : ActorMethod<[PaymentMethod], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContentForApproval' : ActorMethod<[string, string], undefined>,
  'submitCreatorFilm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRevenueModel' : ActorMethod<[RevenueModel], undefined>,
  'updateRoyaltyEarnings' : ActorMethod<[string, bigint], undefined>,
  'verifyCreator' : ActorMethod<[Principal, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];