/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const List = IDL.Rec();
export const List_1 = IDL.Rec();
export const List_2 = IDL.Rec();
export const List_3 = IDL.Rec();
export const List_4 = IDL.Rec();
export const List_5 = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkUploadItem = IDL.Record({
  'title' : IDL.Text,
  'coverImagePath' : IDL.Text,
  'trailerPath' : IDL.Text,
  'description' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const RevenueModel = IDL.Record({
  'merchandise' : IDL.Nat,
  'subscriptionRevenue' : IDL.Nat,
  'adRevenue' : IDL.Nat,
  'payPerView' : IDL.Nat,
  'tipsDonations' : IDL.Nat,
});
export const Time = IDL.Int;
export const AdminApproval = IDL.Record({
  'status' : IDL.Text,
  'contentId' : IDL.Text,
  'creator' : IDL.Principal,
  'feedback' : IDL.Text,
  'approvalDate' : IDL.Opt(Time),
  'submissionDate' : Time,
});
export const CreatorVerification = IDL.Record({
  'status' : IDL.Text,
  'principal' : IDL.Principal,
  'verified' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'verificationDate' : IDL.Opt(Time),
  'creatorType' : IDL.Text,
  'identityDocument' : IDL.Opt(IDL.Text),
  'submissionDate' : Time,
});
export const Movie = IDL.Record({
  'title' : IDL.Text,
  'coverImagePath' : IDL.Text,
  'trailerPath' : IDL.Text,
  'description' : IDL.Text,
  'averageRating' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const PaymentMethod = IDL.Variant({
  'icp' : IDL.Text,
  'mobileMoney' : IDL.Text,
  'stripe' : IDL.Text,
  'usdc' : IDL.Text,
  'usdt' : IDL.Text,
  'tamriWallet' : IDL.Text,
  'crypto' : IDL.Text,
  'paystack' : IDL.Text,
  'plugWallet' : IDL.Text,
  'stoicWallet' : IDL.Text,
  'mPesa' : IDL.Text,
});
export const PayoutRecord = IDL.Record({
  'status' : IDL.Text,
  'method' : PaymentMethod,
  'date' : Time,
  'amount' : IDL.Nat,
});
List_5.fill(IDL.Opt(IDL.Tuple(PayoutRecord, List_5)));
export const RoyaltyEvent = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
  'amount' : IDL.Nat,
  'eventType' : IDL.Text,
});
List_4.fill(IDL.Opt(IDL.Tuple(RoyaltyEvent, List_4)));
export const SmartRoyalty = IDL.Record({
  'contentId' : IDL.Text,
  'creator' : IDL.Principal,
  'payoutHistory' : List_5,
  'lastUpdated' : Time,
  'revenueModel' : RevenueModel,
  'totalEarnings' : IDL.Nat,
  'eventLog' : List_4,
});
List.fill(IDL.Opt(IDL.Tuple(IDL.Text, List)));
export const UserProfile = IDL.Record({
  'watchPartyHistory' : List,
  'favoriteMovies' : List,
  'dataSaverMode' : IDL.Bool,
});
export const CreatorSubmission = IDL.Record({
  'contactInfo' : IDL.Text,
  'filmTitle' : IDL.Text,
  'description' : IDL.Text,
  'creatorName' : IDL.Text,
  'category' : IDL.Text,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconPath' : IDL.Text,
});
export const FeaturedMovie = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'coverImagePath' : IDL.Text,
  'trailerPath' : IDL.Text,
  'description' : IDL.Text,
  'director' : IDL.Text,
  'genre' : IDL.Text,
  'rating' : IDL.Text,
});
export const CreatorShowcase = IDL.Record({
  'profileImage' : IDL.Text,
  'name' : IDL.Text,
  'featuredWork' : IDL.Text,
  'description' : IDL.Text,
});
export const ValueProp = IDL.Record({
  'supportingPoints' : IDL.Vec(IDL.Text),
  'headline' : IDL.Text,
  'description' : IDL.Text,
});
export const TrailerClip = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'videoPath' : IDL.Text,
  'thumbnailPath' : IDL.Text,
});
export const FeaturedContent = IDL.Record({
  'categories' : IDL.Vec(Category),
  'featuredMovies' : IDL.Vec(FeaturedMovie),
  'creatorShowcases' : IDL.Vec(CreatorShowcase),
  'valueProps' : IDL.Vec(ValueProp),
  'trailerClips' : IDL.Vec(TrailerClip),
  'movies' : IDL.Vec(Movie),
});
export const ContentResult = IDL.Variant({
  'fallback' : FeaturedContent,
  'success' : FeaturedContent,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Rating = IDL.Record({ 'review' : IDL.Text, 'score' : IDL.Nat });
export const RevenueShare = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'payoutHistory' : List_5,
  'pendingPayouts' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TopPick = IDL.Record({
  'curatorName' : IDL.Text,
  'recommendation' : IDL.Text,
  'movieTitle' : IDL.Text,
  'reason' : IDL.Text,
});
List_2.fill(IDL.Opt(IDL.Tuple(IDL.Principal, List_2)));
export const Reaction = IDL.Record({
  'user' : IDL.Principal,
  'reactionType' : IDL.Text,
  'timestamp' : Time,
});
List_3.fill(IDL.Opt(IDL.Tuple(Reaction, List_3)));
export const ChatMessage = IDL.Record({
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
List_1.fill(IDL.Opt(IDL.Tuple(ChatMessage, List_1)));
export const WatchParty = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'participants' : List_2,
  'host' : IDL.Principal,
  'isActive' : IDL.Bool,
  'movieTitle' : IDL.Text,
  'reactions' : List_3,
  'chatHistory' : List_1,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFavoriteMovie' : IDL.Func([IDL.Text], [], []),
  'addMovie' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTopPick' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveContent' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUploadMovies' : IDL.Func([IDL.Vec(BulkUploadItem)], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSmartRoyalty' : IDL.Func([IDL.Text, RevenueModel], [], []),
  'createWatchParty' : IDL.Func([IDL.Text], [IDL.Text], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllContentApprovals' : IDL.Func([], [IDL.Vec(AdminApproval)], ['query']),
  'getAllCreatorVerifications' : IDL.Func(
      [],
      [IDL.Vec(CreatorVerification)],
      ['query'],
    ),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllSmartRoyalties' : IDL.Func([], [IDL.Vec(SmartRoyalty)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentApprovalStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdminApproval)],
      ['query'],
    ),
  'getCreatorSubmissions' : IDL.Func(
      [],
      [IDL.Vec(CreatorSubmission)],
      ['query'],
    ),
  'getCreatorVerificationStatus' : IDL.Func(
      [],
      [IDL.Opt(CreatorVerification)],
      ['query'],
    ),
  'getDataSaverMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getFallbackContent' : IDL.Func([], [FeaturedContent], ['query']),
  'getFavoriteMovies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedContent' : IDL.Func([], [ContentResult], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMovie' : IDL.Func([IDL.Text], [IDL.Opt(Movie)], ['query']),
  'getMovieRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
  'getRevenueModel' : IDL.Func([], [RevenueModel], ['query']),
  'getRevenueShare' : IDL.Func([], [RevenueShare], ['query']),
  'getRevenueSharingInfo' : IDL.Func([], [IDL.Vec(RevenueShare)], ['query']),
  'getRoyaltyEvents' : IDL.Func([IDL.Text], [IDL.Vec(RoyaltyEvent)], ['query']),
  'getRoyaltyPayoutHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PayoutRecord)],
      ['query'],
    ),
  'getSmartRoyaltiesByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SmartRoyalty)],
      ['query'],
    ),
  'getSmartRoyalty' : IDL.Func([IDL.Text], [IDL.Opt(SmartRoyalty)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTopPicks' : IDL.Func([], [IDL.Vec(TopPick)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchParty' : IDL.Func([IDL.Text], [IDL.Opt(WatchParty)], ['query']),
  'getWatchPartyHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinWatchParty' : IDL.Func([IDL.Text], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'logRoyaltyEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'rateMovie' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'registerCreator' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeFavoriteMovie' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setDataSaverMode' : IDL.Func([IDL.Bool], [], []),
  'setPaymentMethod' : IDL.Func([PaymentMethod], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContentForApproval' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitCreatorFilm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRevenueModel' : IDL.Func([RevenueModel], [], []),
  'updateRoyaltyEarnings' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'verifyCreator' : IDL.Func([IDL.Principal, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const List = IDL.Rec();
  const List_1 = IDL.Rec();
  const List_2 = IDL.Rec();
  const List_3 = IDL.Rec();
  const List_4 = IDL.Rec();
  const List_5 = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkUploadItem = IDL.Record({
    'title' : IDL.Text,
    'coverImagePath' : IDL.Text,
    'trailerPath' : IDL.Text,
    'description' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const RevenueModel = IDL.Record({
    'merchandise' : IDL.Nat,
    'subscriptionRevenue' : IDL.Nat,
    'adRevenue' : IDL.Nat,
    'payPerView' : IDL.Nat,
    'tipsDonations' : IDL.Nat,
  });
  const Time = IDL.Int;
  const AdminApproval = IDL.Record({
    'status' : IDL.Text,
    'contentId' : IDL.Text,
    'creator' : IDL.Principal,
    'feedback' : IDL.Text,
    'approvalDate' : IDL.Opt(Time),
    'submissionDate' : Time,
  });
  const CreatorVerification = IDL.Record({
    'status' : IDL.Text,
    'principal' : IDL.Principal,
    'verified' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'verificationDate' : IDL.Opt(Time),
    'creatorType' : IDL.Text,
    'identityDocument' : IDL.Opt(IDL.Text),
    'submissionDate' : Time,
  });
  const Movie = IDL.Record({
    'title' : IDL.Text,
    'coverImagePath' : IDL.Text,
    'trailerPath' : IDL.Text,
    'description' : IDL.Text,
    'averageRating' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const PaymentMethod = IDL.Variant({
    'icp' : IDL.Text,
    'mobileMoney' : IDL.Text,
    'stripe' : IDL.Text,
    'usdc' : IDL.Text,
    'usdt' : IDL.Text,
    'tamriWallet' : IDL.Text,
    'crypto' : IDL.Text,
    'paystack' : IDL.Text,
    'plugWallet' : IDL.Text,
    'stoicWallet' : IDL.Text,
    'mPesa' : IDL.Text,
  });
  const PayoutRecord = IDL.Record({
    'status' : IDL.Text,
    'method' : PaymentMethod,
    'date' : Time,
    'amount' : IDL.Nat,
  });
  List_5.fill(IDL.Opt(IDL.Tuple(PayoutRecord, List_5)));
  const RoyaltyEvent = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
    'amount' : IDL.Nat,
    'eventType' : IDL.Text,
  });
  List_4.fill(IDL.Opt(IDL.Tuple(RoyaltyEvent, List_4)));
  const SmartRoyalty = IDL.Record({
    'contentId' : IDL.Text,
    'creator' : IDL.Principal,
    'payoutHistory' : List_5,
    'lastUpdated' : Time,
    'revenueModel' : RevenueModel,
    'totalEarnings' : IDL.Nat,
    'eventLog' : List_4,
  });
  List.fill(IDL.Opt(IDL.Tuple(IDL.Text, List)));
  const UserProfile = IDL.Record({
    'watchPartyHistory' : List,
    'favoriteMovies' : List,
    'dataSaverMode' : IDL.Bool,
  });
  const CreatorSubmission = IDL.Record({
    'contactInfo' : IDL.Text,
    'filmTitle' : IDL.Text,
    'description' : IDL.Text,
    'creatorName' : IDL.Text,
    'category' : IDL.Text,
  });
  const Category = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconPath' : IDL.Text,
  });
  const FeaturedMovie = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'coverImagePath' : IDL.Text,
    'trailerPath' : IDL.Text,
    'description' : IDL.Text,
    'director' : IDL.Text,
    'genre' : IDL.Text,
    'rating' : IDL.Text,
  });
  const CreatorShowcase = IDL.Record({
    'profileImage' : IDL.Text,
    'name' : IDL.Text,
    'featuredWork' : IDL.Text,
    'description' : IDL.Text,
  });
  const ValueProp = IDL.Record({
    'supportingPoints' : IDL.Vec(IDL.Text),
    'headline' : IDL.Text,
    'description' : IDL.Text,
  });
  const TrailerClip = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videoPath' : IDL.Text,
    'thumbnailPath' : IDL.Text,
  });
  const FeaturedContent = IDL.Record({
    'categories' : IDL.Vec(Category),
    'featuredMovies' : IDL.Vec(FeaturedMovie),
    'creatorShowcases' : IDL.Vec(CreatorShowcase),
    'valueProps' : IDL.Vec(ValueProp),
    'trailerClips' : IDL.Vec(TrailerClip),
    'movies' : IDL.Vec(Movie),
  });
  const ContentResult = IDL.Variant({
    'fallback' : FeaturedContent,
    'success' : FeaturedContent,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Rating = IDL.Record({ 'review' : IDL.Text, 'score' : IDL.Nat });
  const RevenueShare = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'payoutHistory' : List_5,
    'pendingPayouts' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TopPick = IDL.Record({
    'curatorName' : IDL.Text,
    'recommendation' : IDL.Text,
    'movieTitle' : IDL.Text,
    'reason' : IDL.Text,
  });
  List_2.fill(IDL.Opt(IDL.Tuple(IDL.Principal, List_2)));
  const Reaction = IDL.Record({
    'user' : IDL.Principal,
    'reactionType' : IDL.Text,
    'timestamp' : Time,
  });
  List_3.fill(IDL.Opt(IDL.Tuple(Reaction, List_3)));
  const ChatMessage = IDL.Record({
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  List_1.fill(IDL.Opt(IDL.Tuple(ChatMessage, List_1)));
  const WatchParty = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'participants' : List_2,
    'host' : IDL.Principal,
    'isActive' : IDL.Bool,
    'movieTitle' : IDL.Text,
    'reactions' : List_3,
    'chatHistory' : List_1,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFavoriteMovie' : IDL.Func([IDL.Text], [], []),
    'addMovie' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTopPick' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveContent' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUploadMovies' : IDL.Func([IDL.Vec(BulkUploadItem)], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSmartRoyalty' : IDL.Func([IDL.Text, RevenueModel], [], []),
    'createWatchParty' : IDL.Func([IDL.Text], [IDL.Text], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllContentApprovals' : IDL.Func(
        [],
        [IDL.Vec(AdminApproval)],
        ['query'],
      ),
    'getAllCreatorVerifications' : IDL.Func(
        [],
        [IDL.Vec(CreatorVerification)],
        ['query'],
      ),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllSmartRoyalties' : IDL.Func([], [IDL.Vec(SmartRoyalty)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentApprovalStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdminApproval)],
        ['query'],
      ),
    'getCreatorSubmissions' : IDL.Func(
        [],
        [IDL.Vec(CreatorSubmission)],
        ['query'],
      ),
    'getCreatorVerificationStatus' : IDL.Func(
        [],
        [IDL.Opt(CreatorVerification)],
        ['query'],
      ),
    'getDataSaverMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getFallbackContent' : IDL.Func([], [FeaturedContent], ['query']),
    'getFavoriteMovies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedContent' : IDL.Func([], [ContentResult], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMovie' : IDL.Func([IDL.Text], [IDL.Opt(Movie)], ['query']),
    'getMovieRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
    'getRevenueModel' : IDL.Func([], [RevenueModel], ['query']),
    'getRevenueShare' : IDL.Func([], [RevenueShare], ['query']),
    'getRevenueSharingInfo' : IDL.Func([], [IDL.Vec(RevenueShare)], ['query']),
    'getRoyaltyEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RoyaltyEvent)],
        ['query'],
      ),
    'getRoyaltyPayoutHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PayoutRecord)],
        ['query'],
      ),
    'getSmartRoyaltiesByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SmartRoyalty)],
        ['query'],
      ),
    'getSmartRoyalty' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SmartRoyalty)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTopPicks' : IDL.Func([], [IDL.Vec(TopPick)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchParty' : IDL.Func([IDL.Text], [IDL.Opt(WatchParty)], ['query']),
    'getWatchPartyHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinWatchParty' : IDL.Func([IDL.Text], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'logRoyaltyEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'rateMovie' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'registerCreator' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeFavoriteMovie' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setDataSaverMode' : IDL.Func([IDL.Bool], [], []),
    'setPaymentMethod' : IDL.Func([PaymentMethod], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContentForApproval' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitCreatorFilm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRevenueModel' : IDL.Func([RevenueModel], [], []),
    'updateRoyaltyEarnings' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'verifyCreator' : IDL.Func([IDL.Principal, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };