/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Movie {
    title: string;
    coverImagePath: string;
    trailerPath: string;
    description: string;
    averageRating: bigint;
    reviewCount: bigint;
}
export interface WatchParty {
    id: string;
    startTime: Time;
    participants: List_2;
    host: Principal;
    isActive: boolean;
    movieTitle: string;
    reactions: List_3;
    chatHistory: List_1;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TrailerClip {
    title: string;
    description: string;
    videoPath: string;
    thumbnailPath: string;
}
export interface TopPick {
    curatorName: string;
    recommendation: string;
    movieTitle: string;
    reason: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Time = bigint;
export interface Rating {
    review: string;
    score: bigint;
}
export interface PayoutRecord {
    status: string;
    method: PaymentMethod;
    date: Time;
    amount: bigint;
}
export type PaymentMethod = {
    __kind__: "icp";
    icp: string;
} | {
    __kind__: "mobileMoney";
    mobileMoney: string;
} | {
    __kind__: "stripe";
    stripe: string;
} | {
    __kind__: "usdc";
    usdc: string;
} | {
    __kind__: "usdt";
    usdt: string;
} | {
    __kind__: "tamriWallet";
    tamriWallet: string;
} | {
    __kind__: "crypto";
    crypto: string;
} | {
    __kind__: "paystack";
    paystack: string;
} | {
    __kind__: "plugWallet";
    plugWallet: string;
} | {
    __kind__: "stoicWallet";
    stoicWallet: string;
} | {
    __kind__: "mPesa";
    mPesa: string;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type List_2 = [Principal, List_2] | null;
export interface CreatorVerification {
    status: string;
    principal: Principal;
    verified: boolean;
    contactInfo: string;
    verificationDate?: Time;
    creatorType: string;
    identityDocument?: string;
    submissionDate: Time;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface CreatorSubmission {
    contactInfo: string;
    filmTitle: string;
    description: string;
    creatorName: string;
    category: string;
}
export interface FeaturedMovie {
    id: string;
    title: string;
    coverImagePath: string;
    trailerPath: string;
    description: string;
    director: string;
    genre: string;
    rating: string;
}
export type List_5 = [PayoutRecord, List_5] | null;
export interface CreatorShowcase {
    profileImage: string;
    name: string;
    featuredWork: string;
    description: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type List = [string, List] | null;
export interface ChatMessage {
    sender: Principal;
    message: string;
    timestamp: Time;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SmartRoyalty {
    contentId: string;
    creator: Principal;
    payoutHistory: List_5;
    lastUpdated: Time;
    revenueModel: RevenueModel;
    totalEarnings: bigint;
    eventLog: List_4;
}
export interface RevenueShare {
    paymentMethod: PaymentMethod;
    payoutHistory: List_5;
    pendingPayouts: bigint;
    totalEarnings: bigint;
}
export interface FileReference {
    hash: string;
    path: string;
}
export type ContentResult = {
    __kind__: "fallback";
    fallback: FeaturedContent;
} | {
    __kind__: "success";
    success: FeaturedContent;
};
export interface Category {
    name: string;
    description: string;
    iconPath: string;
}
export interface BulkUploadItem {
    title: string;
    coverImagePath: string;
    trailerPath: string;
    description: string;
}
export interface AdminApproval {
    status: string;
    contentId: string;
    creator: Principal;
    feedback: string;
    approvalDate?: Time;
    submissionDate: Time;
}
export type List_3 = [Reaction, List_3] | null;
export interface RevenueModel {
    merchandise: bigint;
    subscriptionRevenue: bigint;
    adRevenue: bigint;
    payPerView: bigint;
    tipsDonations: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RoyaltyEvent {
    user: Principal;
    timestamp: Time;
    details: string;
    amount: bigint;
    eventType: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface FeaturedContent {
    categories: Array<Category>;
    featuredMovies: Array<FeaturedMovie>;
    creatorShowcases: Array<CreatorShowcase>;
    valueProps: Array<ValueProp>;
    trailerClips: Array<TrailerClip>;
    movies: Array<Movie>;
}
export interface ValueProp {
    supportingPoints: Array<string>;
    headline: string;
    description: string;
}
export type List_1 = [ChatMessage, List_1] | null;
export type List_4 = [RoyaltyEvent, List_4] | null;
export interface UserProfile {
    watchPartyHistory: List;
    favoriteMovies: List;
    dataSaverMode: boolean;
}
export interface Reaction {
    user: Principal;
    reactionType: string;
    timestamp: Time;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addFavoriteMovie(movieTitle: string): Promise<void>;
    addMovie(title: string, description: string, coverImagePath: string, trailerPath: string): Promise<void>;
    addReaction(partyId: string, reactionType: string): Promise<void>;
    addTopPick(movieTitle: string, curatorName: string, recommendation: string, reason: string): Promise<void>;
    approveContent(contentId: string, approved: boolean, feedback: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUploadMovies(items: Array<BulkUploadItem>): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createSmartRoyalty(contentId: string, revenueModel: RevenueModel): Promise<void>;
    createWatchParty(movieTitle: string): Promise<string>;
    dropFileReference(path: string): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAllContentApprovals(): Promise<Array<AdminApproval>>;
    getAllCreatorVerifications(): Promise<Array<CreatorVerification>>;
    getAllMovies(): Promise<Array<Movie>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllSmartRoyalties(): Promise<Array<SmartRoyalty>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContentApprovalStatus(contentId: string): Promise<AdminApproval | null>;
    getCreatorSubmissions(): Promise<Array<CreatorSubmission>>;
    getCreatorVerificationStatus(): Promise<CreatorVerification | null>;
    getDataSaverMode(): Promise<boolean>;
    getFallbackContent(): Promise<FeaturedContent>;
    getFavoriteMovies(): Promise<Array<string>>;
    getFeaturedContent(): Promise<ContentResult>;
    getFileReference(path: string): Promise<FileReference>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getMovie(title: string): Promise<Movie | null>;
    getMovieRatings(movieTitle: string): Promise<Array<Rating>>;
    getRevenueModel(): Promise<RevenueModel>;
    getRevenueShare(): Promise<RevenueShare>;
    getRevenueSharingInfo(): Promise<Array<RevenueShare>>;
    getRoyaltyEvents(contentId: string): Promise<Array<RoyaltyEvent>>;
    getRoyaltyPayoutHistory(contentId: string): Promise<Array<PayoutRecord>>;
    getSmartRoyaltiesByCreator(creator: Principal): Promise<Array<SmartRoyalty>>;
    getSmartRoyalty(contentId: string): Promise<SmartRoyalty | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTopPicks(): Promise<Array<TopPick>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWatchParty(partyId: string): Promise<WatchParty | null>;
    getWatchPartyHistory(): Promise<Array<string>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    joinWatchParty(partyId: string): Promise<void>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listFileReferences(): Promise<Array<FileReference>>;
    logRoyaltyEvent(contentId: string, eventType: string, amount: bigint, details: string): Promise<void>;
    rateMovie(movieTitle: string, score: bigint, review: string): Promise<void>;
    registerCreator(contactInfo: string, creatorType: string, identityDocument: string | null): Promise<void>;
    registerFileReference(path: string, hash: string): Promise<void>;
    removeFavoriteMovie(movieTitle: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchMovies(searchTerm: string): Promise<Array<Movie>>;
    sendChatMessage(partyId: string, message: string): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setDataSaverMode(enabled: boolean): Promise<void>;
    setPaymentMethod(method: PaymentMethod): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitContentForApproval(contentId: string, feedback: string): Promise<void>;
    submitCreatorFilm(filmTitle: string, description: string, creatorName: string, contactInfo: string, category: string): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateRevenueModel(newRevenueModel: RevenueModel): Promise<void>;
    updateRoyaltyEarnings(contentId: string, amount: bigint): Promise<void>;
    verifyCreator(creator: Principal, verified: boolean, feedback: string): Promise<void>;
}
import type { AdminApproval as _AdminApproval, ApprovalStatus as _ApprovalStatus, ChatMessage as _ChatMessage, ContentResult as _ContentResult, CreatorVerification as _CreatorVerification, FeaturedContent as _FeaturedContent, List as _List, List_1 as _List_1, List_2 as _List_2, List_3 as _List_3, List_4 as _List_4, List_5 as _List_5, Movie as _Movie, PaymentMethod as _PaymentMethod, PayoutRecord as _PayoutRecord, Reaction as _Reaction, RevenueModel as _RevenueModel, RevenueShare as _RevenueShare, RoyaltyEvent as _RoyaltyEvent, SmartRoyalty as _SmartRoyalty, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, WatchParty as _WatchParty, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addFavoriteMovie(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteMovie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteMovie(arg0);
            return result;
        }
    }
    async addMovie(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMovie(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMovie(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addReaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return result;
        }
    }
    async addTopPick(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTopPick(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTopPick(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveContent(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveContent(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUploadMovies(arg0: Array<BulkUploadItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadMovies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadMovies(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createSmartRoyalty(arg0: string, arg1: RevenueModel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSmartRoyalty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSmartRoyalty(arg0, arg1);
            return result;
        }
    }
    async createWatchParty(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWatchParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWatchParty(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllContentApprovals(): Promise<Array<AdminApproval>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentApprovals();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentApprovals();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCreatorVerifications(): Promise<Array<CreatorVerification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCreatorVerifications();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCreatorVerifications();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMovies(): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMovies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMovies();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllSmartRoyalties(): Promise<Array<SmartRoyalty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSmartRoyalties();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSmartRoyalties();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentApprovalStatus(arg0: string): Promise<AdminApproval | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentApprovalStatus(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentApprovalStatus(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorSubmissions(): Promise<Array<CreatorSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorSubmissions();
            return result;
        }
    }
    async getCreatorVerificationStatus(): Promise<CreatorVerification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorVerificationStatus();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorVerificationStatus();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataSaverMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataSaverMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataSaverMode();
            return result;
        }
    }
    async getFallbackContent(): Promise<FeaturedContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getFallbackContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFallbackContent();
            return result;
        }
    }
    async getFavoriteMovies(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoriteMovies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoriteMovies();
            return result;
        }
    }
    async getFeaturedContent(): Promise<ContentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedContent();
                return from_candid_ContentResult_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedContent();
            return from_candid_ContentResult_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getMovie(arg0: string): Promise<Movie | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovie(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovie(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMovieRatings(arg0: string): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovieRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovieRatings(arg0);
            return result;
        }
    }
    async getRevenueModel(): Promise<RevenueModel> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueModel();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueModel();
            return result;
        }
    }
    async getRevenueShare(): Promise<RevenueShare> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueShare();
                return from_candid_RevenueShare_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueShare();
            return from_candid_RevenueShare_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueSharingInfo(): Promise<Array<RevenueShare>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueSharingInfo();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueSharingInfo();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoyaltyEvents(arg0: string): Promise<Array<RoyaltyEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoyaltyEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoyaltyEvents(arg0);
            return result;
        }
    }
    async getRoyaltyPayoutHistory(arg0: string): Promise<Array<PayoutRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoyaltyPayoutHistory(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoyaltyPayoutHistory(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmartRoyaltiesByCreator(arg0: Principal): Promise<Array<SmartRoyalty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmartRoyaltiesByCreator(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmartRoyaltiesByCreator(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmartRoyalty(arg0: string): Promise<SmartRoyalty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmartRoyalty(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmartRoyalty(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopPicks(): Promise<Array<TopPick>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPicks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPicks();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchParty(arg0: string): Promise<WatchParty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchParty(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchParty(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchPartyHistory(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchPartyHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchPartyHistory();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async joinWatchParty(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinWatchParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinWatchParty(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async logRoyaltyEvent(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logRoyaltyEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logRoyaltyEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rateMovie(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateMovie(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateMovie(arg0, arg1, arg2);
            return result;
        }
    }
    async registerCreator(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCreator(arg0, arg1, to_candid_opt_n69(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCreator(arg0, arg1, to_candid_opt_n69(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async removeFavoriteMovie(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteMovie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteMovie(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n70(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n70(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchMovies(arg0: string): Promise<Array<Movie>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMovies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMovies(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n75(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n75(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setDataSaverMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDataSaverMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDataSaverMode(arg0);
            return result;
        }
    }
    async setPaymentMethod(arg0: PaymentMethod): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentMethod(to_candid_PaymentMethod_n77(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentMethod(to_candid_PaymentMethod_n77(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitContentForApproval(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContentForApproval(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContentForApproval(arg0, arg1);
            return result;
        }
    }
    async submitCreatorFilm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCreatorFilm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCreatorFilm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateRevenueModel(arg0: RevenueModel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRevenueModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRevenueModel(arg0);
            return result;
        }
    }
    async updateRoyaltyEarnings(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoyaltyEarnings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoyaltyEarnings(arg0, arg1);
            return result;
        }
    }
    async verifyCreator(arg0: Principal, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCreator(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCreator(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AdminApproval_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminApproval): AdminApproval {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_ContentResult_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentResult): ContentResult {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_CreatorVerification_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorVerification): CreatorVerification {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_List_1_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List_1): List_1 {
    return from_candid_opt_n62(_uploadFile, _downloadFile, value);
}
function from_candid_List_2_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List_2): List_2 {
    return from_candid_opt_n56(_uploadFile, _downloadFile, value);
}
function from_candid_List_3_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List_3): List_3 {
    return from_candid_opt_n59(_uploadFile, _downloadFile, value);
}
function from_candid_List_4_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List_4): List_4 {
    return from_candid_opt_n29(_uploadFile, _downloadFile, value);
}
function from_candid_List_5_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List_5): List_5 {
    return from_candid_opt_n22(_uploadFile, _downloadFile, value);
}
function from_candid_List_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List): List {
    return from_candid_opt_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutRecord_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutRecord): PayoutRecord {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueShare_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueShare): RevenueShare {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_SmartRoyalty_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SmartRoyalty): SmartRoyalty {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_WatchParty_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WatchParty): WatchParty {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_PayoutRecord, _List_5]]): [PayoutRecord, List_5] | null {
    return value.length === 0 ? null : from_candid_tuple_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_RoyaltyEvent, _List_4]]): [RoyaltyEvent, List_4] | null {
    return value.length === 0 ? null : from_candid_tuple_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[string, _List]]): [string, List] | null {
    return value.length === 0 ? null : from_candid_tuple_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminApproval]): AdminApproval | null {
    return value.length === 0 ? null : from_candid_AdminApproval_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CreatorVerification]): CreatorVerification | null {
    return value.length === 0 ? null : from_candid_CreatorVerification_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Movie]): Movie | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SmartRoyalty]): SmartRoyalty | null {
    return value.length === 0 ? null : from_candid_SmartRoyalty_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WatchParty]): WatchParty | null {
    return value.length === 0 ? null : from_candid_WatchParty_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[Principal, _List_2]]): [Principal, List_2] | null {
    return value.length === 0 ? null : from_candid_tuple_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_Reaction, _List_3]]): [Reaction, List_3] | null {
    return value.length === 0 ? null : from_candid_tuple_n60(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_ChatMessage, _List_1]]): [ChatMessage, List_1] | null {
    return value.length === 0 ? null : from_candid_tuple_n63(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    contentId: string;
    creator: Principal;
    feedback: string;
    approvalDate: [] | [_Time];
    submissionDate: _Time;
}): {
    status: string;
    contentId: string;
    creator: Principal;
    feedback: string;
    approvalDate?: Time;
    submissionDate: Time;
} {
    return {
        status: value.status,
        contentId: value.contentId,
        creator: value.creator,
        feedback: value.feedback,
        approvalDate: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.approvalDate)),
        submissionDate: value.submissionDate
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    principal: Principal;
    verified: boolean;
    contactInfo: string;
    verificationDate: [] | [_Time];
    creatorType: string;
    identityDocument: [] | [string];
    submissionDate: _Time;
}): {
    status: string;
    principal: Principal;
    verified: boolean;
    contactInfo: string;
    verificationDate?: Time;
    creatorType: string;
    identityDocument?: string;
    submissionDate: Time;
} {
    return {
        status: value.status,
        principal: value.principal,
        verified: value.verified,
        contactInfo: value.contactInfo,
        verificationDate: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.verificationDate)),
        creatorType: value.creatorType,
        identityDocument: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.identityDocument)),
        submissionDate: value.submissionDate
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentId: string;
    creator: Principal;
    payoutHistory: _List_5;
    lastUpdated: _Time;
    revenueModel: _RevenueModel;
    totalEarnings: bigint;
    eventLog: _List_4;
}): {
    contentId: string;
    creator: Principal;
    payoutHistory: List_5;
    lastUpdated: Time;
    revenueModel: RevenueModel;
    totalEarnings: bigint;
    eventLog: List_4;
} {
    return {
        contentId: value.contentId,
        creator: value.creator,
        payoutHistory: from_candid_List_5_n21(_uploadFile, _downloadFile, value.payoutHistory),
        lastUpdated: value.lastUpdated,
        revenueModel: value.revenueModel,
        totalEarnings: value.totalEarnings,
        eventLog: from_candid_List_4_n28(_uploadFile, _downloadFile, value.eventLog)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    method: _PaymentMethod;
    date: _Time;
    amount: bigint;
}): {
    status: string;
    method: PaymentMethod;
    date: Time;
    amount: bigint;
} {
    return {
        status: value.status,
        method: from_candid_PaymentMethod_n26(_uploadFile, _downloadFile, value.method),
        date: value.date,
        amount: value.amount
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    watchPartyHistory: _List;
    favoriteMovies: _List;
    dataSaverMode: boolean;
}): {
    watchPartyHistory: List;
    favoriteMovies: List;
    dataSaverMode: boolean;
} {
    return {
        watchPartyHistory: from_candid_List_n34(_uploadFile, _downloadFile, value.watchPartyHistory),
        favoriteMovies: from_candid_List_n34(_uploadFile, _downloadFile, value.favoriteMovies),
        dataSaverMode: value.dataSaverMode
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: _PaymentMethod;
    payoutHistory: _List_5;
    pendingPayouts: bigint;
    totalEarnings: bigint;
}): {
    paymentMethod: PaymentMethod;
    payoutHistory: List_5;
    pendingPayouts: bigint;
    totalEarnings: bigint;
} {
    return {
        paymentMethod: from_candid_PaymentMethod_n26(_uploadFile, _downloadFile, value.paymentMethod),
        payoutHistory: from_candid_List_5_n21(_uploadFile, _downloadFile, value.payoutHistory),
        pendingPayouts: value.pendingPayouts,
        totalEarnings: value.totalEarnings
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    participants: _List_2;
    host: Principal;
    isActive: boolean;
    movieTitle: string;
    reactions: _List_3;
    chatHistory: _List_1;
}): {
    id: string;
    startTime: Time;
    participants: List_2;
    host: Principal;
    isActive: boolean;
    movieTitle: string;
    reactions: List_3;
    chatHistory: List_1;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        participants: from_candid_List_2_n55(_uploadFile, _downloadFile, value.participants),
        host: value.host,
        isActive: value.isActive,
        movieTitle: value.movieTitle,
        reactions: from_candid_List_3_n58(_uploadFile, _downloadFile, value.reactions),
        chatHistory: from_candid_List_1_n61(_uploadFile, _downloadFile, value.chatHistory)
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n67(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PayoutRecord, _List_5]): [PayoutRecord, List_5] {
    return [
        from_candid_PayoutRecord_n24(_uploadFile, _downloadFile, value[0]),
        from_candid_List_5_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_RoyaltyEvent, _List_4]): [RoyaltyEvent, List_4] {
    return [
        value[0],
        from_candid_List_4_n28(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _List]): [string, List] {
    return [
        value[0],
        from_candid_List_n34(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _List_2]): [Principal, List_2] {
    return [
        value[0],
        from_candid_List_2_n55(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Reaction, _List_3]): [Reaction, List_3] {
    return [
        value[0],
        from_candid_List_3_n58(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ChatMessage, _List_1]): [ChatMessage, List_1] {
    return [
        value[0],
        from_candid_List_1_n61(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    icp: string;
} | {
    mobileMoney: string;
} | {
    stripe: string;
} | {
    usdc: string;
} | {
    usdt: string;
} | {
    tamriWallet: string;
} | {
    crypto: string;
} | {
    paystack: string;
} | {
    plugWallet: string;
} | {
    stoicWallet: string;
} | {
    mPesa: string;
}): {
    __kind__: "icp";
    icp: string;
} | {
    __kind__: "mobileMoney";
    mobileMoney: string;
} | {
    __kind__: "stripe";
    stripe: string;
} | {
    __kind__: "usdc";
    usdc: string;
} | {
    __kind__: "usdt";
    usdt: string;
} | {
    __kind__: "tamriWallet";
    tamriWallet: string;
} | {
    __kind__: "crypto";
    crypto: string;
} | {
    __kind__: "paystack";
    paystack: string;
} | {
    __kind__: "plugWallet";
    plugWallet: string;
} | {
    __kind__: "stoicWallet";
    stoicWallet: string;
} | {
    __kind__: "mPesa";
    mPesa: string;
} {
    return "icp" in value ? {
        __kind__: "icp",
        icp: value.icp
    } : "mobileMoney" in value ? {
        __kind__: "mobileMoney",
        mobileMoney: value.mobileMoney
    } : "stripe" in value ? {
        __kind__: "stripe",
        stripe: value.stripe
    } : "usdc" in value ? {
        __kind__: "usdc",
        usdc: value.usdc
    } : "usdt" in value ? {
        __kind__: "usdt",
        usdt: value.usdt
    } : "tamriWallet" in value ? {
        __kind__: "tamriWallet",
        tamriWallet: value.tamriWallet
    } : "crypto" in value ? {
        __kind__: "crypto",
        crypto: value.crypto
    } : "paystack" in value ? {
        __kind__: "paystack",
        paystack: value.paystack
    } : "plugWallet" in value ? {
        __kind__: "plugWallet",
        plugWallet: value.plugWallet
    } : "stoicWallet" in value ? {
        __kind__: "stoicWallet",
        stoicWallet: value.stoicWallet
    } : "mPesa" in value ? {
        __kind__: "mPesa",
        mPesa: value.mPesa
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fallback: _FeaturedContent;
} | {
    success: _FeaturedContent;
}): {
    __kind__: "fallback";
    fallback: FeaturedContent;
} | {
    __kind__: "success";
    success: FeaturedContent;
} {
    return "fallback" in value ? {
        __kind__: "fallback",
        fallback: value.fallback
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n51(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminApproval>): Array<AdminApproval> {
    return value.map((x)=>from_candid_AdminApproval_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreatorVerification>): Array<CreatorVerification> {
    return value.map((x)=>from_candid_CreatorVerification_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SmartRoyalty>): Array<SmartRoyalty> {
    return value.map((x)=>from_candid_SmartRoyalty_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RevenueShare>): Array<RevenueShare> {
    return value.map((x)=>from_candid_RevenueShare_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PayoutRecord>): Array<PayoutRecord> {
    return value.map((x)=>from_candid_PayoutRecord_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n65(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_List_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: List): _List {
    return to_candid_opt_n73(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, List] | null): [] | [[string, _List]] {
    return value === null ? candid_none() : candid_some(to_candid_tuple_n74(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    watchPartyHistory: List;
    favoriteMovies: List;
    dataSaverMode: boolean;
}): {
    watchPartyHistory: _List;
    favoriteMovies: _List;
    dataSaverMode: boolean;
} {
    return {
        watchPartyHistory: to_candid_List_n72(_uploadFile, _downloadFile, value.watchPartyHistory),
        favoriteMovies: to_candid_List_n72(_uploadFile, _downloadFile, value.favoriteMovies),
        dataSaverMode: value.dataSaverMode
    };
}
function to_candid_tuple_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, List]): [string, _List] {
    return [
        value[0],
        to_candid_List_n72(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "icp";
    icp: string;
} | {
    __kind__: "mobileMoney";
    mobileMoney: string;
} | {
    __kind__: "stripe";
    stripe: string;
} | {
    __kind__: "usdc";
    usdc: string;
} | {
    __kind__: "usdt";
    usdt: string;
} | {
    __kind__: "tamriWallet";
    tamriWallet: string;
} | {
    __kind__: "crypto";
    crypto: string;
} | {
    __kind__: "paystack";
    paystack: string;
} | {
    __kind__: "plugWallet";
    plugWallet: string;
} | {
    __kind__: "stoicWallet";
    stoicWallet: string;
} | {
    __kind__: "mPesa";
    mPesa: string;
}): {
    icp: string;
} | {
    mobileMoney: string;
} | {
    stripe: string;
} | {
    usdc: string;
} | {
    usdt: string;
} | {
    tamriWallet: string;
} | {
    crypto: string;
} | {
    paystack: string;
} | {
    plugWallet: string;
} | {
    stoicWallet: string;
} | {
    mPesa: string;
} {
    return value.__kind__ === "icp" ? {
        icp: value.icp
    } : value.__kind__ === "mobileMoney" ? {
        mobileMoney: value.mobileMoney
    } : value.__kind__ === "stripe" ? {
        stripe: value.stripe
    } : value.__kind__ === "usdc" ? {
        usdc: value.usdc
    } : value.__kind__ === "usdt" ? {
        usdt: value.usdt
    } : value.__kind__ === "tamriWallet" ? {
        tamriWallet: value.tamriWallet
    } : value.__kind__ === "crypto" ? {
        crypto: value.crypto
    } : value.__kind__ === "paystack" ? {
        paystack: value.paystack
    } : value.__kind__ === "plugWallet" ? {
        plugWallet: value.plugWallet
    } : value.__kind__ === "stoicWallet" ? {
        stoicWallet: value.stoicWallet
    } : value.__kind__ === "mPesa" ? {
        mPesa: value.mPesa
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
